### ISSUE TITLE
A quick note on the returnDataFrame parameter of select_metadata()

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/ffmetadata#15]
I found this section a bit confusing.  I think it might be better with an example.  With an example I'm not sure that it would even need its own section heading.

**Comment by rvinh** [comment]
Example added, unnecessary description removed

**Comment by msalganik** [comment]
Great

**Comment by msalganik** [comment]
Can you also please add a print statement for
select <- select_metadata(variable_name = "ce3datey", fields = c("data_source", "data_type"))
select_full <- select_metadata(variable_name = "ce3datey")
and
select_return_list <- select_metadata(variable_name = "ce3datey", returnDataFrame = FALSE)

I think that seeing the different kinds of output will really help people understand what is going with the returnDataFrame option.

**Comment by rvinh** [comment]
I added formatted print statements for each way of using select_metadata, but the formatting looks a little strange for the select_full <- select_metadata(variable_name = "ce3datey") call.  At the moment, I've split the row up into multiple lines but I could also have one long row extend off the page if that would be clearer/preferred.

**Comment by msalganik** [comment]
Interesting.  That's not what I expected at all.  Is there a way to make the printing more what it looks like in the console?  That's what it used to look like.

**Comment by msalganik** [comment]
Here's an example of a vignette where the print statements look more like what one would see in the R terminal: https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html

**Comment by rvinh** [comment]
I was using Pander to format the data frames into tables in the version from yesterday.  I've reverted it to just the native console format.

**Comment by msalganik** [comment]
OK, I think that looks good.  It is not very pretty, but it gives users a good sense of what to expect (and it matches the style of other vignettes).  As far as I'm concerned, this issue is closed.  If you agree, please close it.

**Comment by rvinh** [comment]
Ok great!
