### ISSUE TITLE
return object for search_metadata()

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/ffmetadata#16]
The vingette says: "search_metadata() allows users to search for variables based on specified field values. This function returns a list of all the variable names that match the specified parameters."

Is it true that this returns a list?  I would have guessed it returns a vector.

**Comment by msalganik** [comment]
While we are working on the vignette, I'd like to get this one resolved too.  What is the return format for search_metadata()?

**Comment by msalganik** [comment]
oppps.  Just read your email.  Sorry!

**Comment by rvinh** [comment]
Just checked, the return format for search_metadata() is actually a list.  Would you prefer a vector to be returned instead?

**Comment by msalganik** [comment]
I don't have a strong opinion about list vs vector so let's keep it the way it is.  The vignette is correct as written so I'm closing this issue.

**Comment by rvinh** [comment]
Sounds good
