### ISSUE TITLE
Activate package website

### ISSUE THREAD

**Issue by conjugateprior** [fragilefamilieschallenge/ffmetadata#2]
I've committed a docs folder onto master. If someone with access to the repo settings would like to switch on GitHub Pages and set the source to “master branch /docs folder” then a dedicated website for the package will appear at https://fragilefamilieschallenge.github.io/ffmetadata

**Comment by conjugateprior** [comment]
This was generated by (https://github.com/r-lib/pkgdown) and can be updated with each release using `pkgdown::build_site()`.

**Comment by msalganik** [comment]
Done.  And the page is up and running: https://fragilefamilieschallenge.github.io/ffmetadata/index.html

Thanks @conjugateprior.
