### ISSUE TITLE
Support operators other than AND

### ISSUE THREAD

**Issue by rvinh** [fragilefamilieschallenge/ffmetadata#20]

**Comment by rvinh** [comment]
Need to implement the "like", relational, "in", and "null" operators

**Comment by rvinh** [comment]
Support added, but needs to be tested further

**Comment by msalganik** [comment]
Thanks @rvinh.  If you think more tests are need, can you create an issue for that with a description of the kinds of tests that you think will be helpful? That will help us keep track of things.

**Comment by rvinh** [comment]
@msalganik I just added some more specifics to the open issue on unit tests!
