### ISSUE TITLE
point to new web endpoints

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/ffmetadata#6]
We are shutting down the old web endpoints so you should update the package to point to the new ones.  The API endpoints have not changed (yet).  The only thing that is changing is the location.  Here's how Vineet did it with the python package: https://github.com/fragilefamilieschallenge/ffmetadata-py/commit/82199d44d5867da45b8c6108aac14b618e9ff9ef

**Comment by msalganik** [comment]
@rvinh I believe that this is complete.  If so, please close.

**Comment by rvinh** [comment]
The endpoints were updated in the latest merge (authored by me)
